version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    # volumes:
    #   - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp=unconfined
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migration:
    image: ubuntu:20.04
    container_name: migration
    depends_on:
      - mysql
    command: bash -c "apt-get update && \
                      apt-get install -y gnupg curl lsb-release ca-certificates && \
                      curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add - && \
                      echo \"deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ focal main\" > /etc/apt/sources.list.d/migrate.list && \
                      apt-get update && \ 
                      apt-get install -y migrate && \
                      migrate -path=sql/migrations -database \"mysql://root:root@tcp(mysql:3306)/orders\" -verbose up"
    volumes:
      - ./sql/migrations:/sql/migrations:rw

  ordersystem:
    build: .
    container_name: ordersystem
    depends_on:
      - mysql
      - migration
      - rabbitmq
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    entrypoint: ["/app/wait-for-it.sh", "mysql", "3306", "--", "/app/wait-for-it.sh", "rabbitmq", "5672", "--", "/app/ordersystem"]      
